name: NodeJS
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup_nodejs
        name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: yarn
      - id: install_dependencies
        name: Install Dependencies
        run: yarn install --frozen-lockfile
      - id: build
        name: Build
        run: yarn build
      - id: generate_pages_artifact
        name: Generate Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
  deploy:
    name: Deploy
    needs:
      - build
    if: ${{github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')}}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{steps.deploy_pages.outputs.page_url}}
    steps:
      - id: deploy_pages
        name: Deploy Pages
        uses: actions/deploy-pages@v1
